org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.10
curios_version=5.14.1+1.20.1
thaumic_reborn_api_version=1.1.0
forge_version_range=[47.4.10,48)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=thaumic_reborn
mod_name=Thaumic Reborn
mod_artifact_name=thaumic-reborn
mod_license=All Rights Reserved
mod_version=1.7.3
mod_group_id=com.thaumcraftmodern
mod_authors=Evgenii
mod_description=Thaumic Reborn is a faithful private-development port of Thaumcraft 4.2.3.5 to Forge 1.20.1, including its modernized world foundation.
